//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vkr_Aralbaeva.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Service1 = new HashSet<Service>();
        }
    
        public int IdOrder { get; set; }
        public int IdCustomer { get; set; }
        public System.DateTime DateOfOrder { get; set; }
        public System.DateTime DateOfService { get; set; }
        public int IdWorker { get; set; }
        public int IdService { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service1 { get; set; }
    }
}
